version: '3'

services:
  the_eye:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./the_eye:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"

    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file:
      - ./.env.dev
    volumes: 
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
        - "6379:6379"
  celery:
    restart: always
    build:
      context: .
    command: celery -A the_eye worker -l info
    volumes:
      - ./the_eye:/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - the_eye
volumes:
  pgdata: