# Generated by Django 4.0.3 on 2022-04-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
